### ISSUE TITLE
Error when using player search

### ISSUE THREAD

**Issue by mcbgun** [olimorris/PyScoutFM#6]
Hi,
[Error.txt](https://github.com/olimorris/PyScoutFM/files/13785811/Error.txt)

Firstly well done...I can see the quality of work on show with this great program! For me the squad screen works perfectly, I got the html output as per your screenshots. However, when I try to run the same for the player search screen I get the following error output. I'm not sure if it's a me thing or a program thing? One other question I have is does the program aggregate the range values to a median value like squirrel's? Not sure whether the below is linked to players not fully scouted?

Thanks again!

**Comment by olimorris** [comment]
Thanks for raising the issue. 

Could you paste the HTML file you're working with and then I can take a look? You should be able to to upload it here:

![2023-12-28 11_04_35 - Safari@2x](https://github.com/olimorris/PyScoutFM/assets/9512444/f0f966c0-352e-44e5-ba02-a54d9d85e28d)

> One other question I have is does the program aggregate the range values to a median value like squirrel's

Good question. I really need to add a section explaining how the app works. Currently, the app evaluates the HTML file you've exported against the weightings which either you specify or the app's defaults. It works out, for every position, what the maximum possible score _could_ be given the weightings. Then it works out what the individual player scored against the weightings and divides that over the maximum possible score. This enables us to have a percentage score.

I think the advantage of my approach is if you decide you want to adjust the weightings for a given position the score will always be out of 100%.

**Comment by mcbgun** [comment]
> Thanks for raising the issue.
> 
> Could you paste the HTML file you're working with and then I can take a look? You should be able to to upload it here:
> 
> ![2023-12-28 11_04_35 - Safari@2x](https://private-user-images.githubusercontent.com/9512444/293193965-f0f966c0-352e-44e5-ba02-a54d9d85e28d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjIwNzMsIm5iZiI6MTcwMzc2MTc3MywicGF0aCI6Ii85NTEyNDQ0LzI5MzE5Mzk2NS1mMGY5NjZjMC0zNTJlLTQ0ZTUtYmEwMi1hNTRkOWQ4NWUyOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTEwOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjMzYjVlMjI1MDRlOTg1NDM1ZjZlMzVkZGU0ODljMWM1ZWEyYjE4ZGU0YWQwMmM1MTUyMTM4NzY4MTI5YzYyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CLl4bfqho-QduSyKk7kuQh_09bwIEWphOoCYLuBrG_U)
> 
> > One other question I have is does the program aggregate the range values to a median value like squirrel's
> 
> Good question. I really need to add a section explaining how the app works. Currently, the app evaluates the HTML file you've exported against the weightings which either you specify or the app's defaults. It works out, for every position, what the maximum possible score _could_ be given the weightings. Then it works out what the individual player scored against the weightings and divides that over the maximum possible score. This enables us to have a percentage score.
> 
> I think the advantage of my approach is if you decide you want to adjust the weightings for a given position the score will always be out of 100%.

Hi thanks for such a quick response! It's not letting me add the html file unfortunately as it's not a supported file type. I've zipped it up for you though. Hopefully that works! Makes sense as well what you've said about the evaluation. :)
[test.zip](https://github.com/olimorris/PyScoutFM/files/13785944/test.zip)

**Comment by olimorris** [comment]
Great thanks. Yep can confirm the issue is because `Luismi Corrales` has not been fully scouted and has attributes like `1-7`. What I'll do is put a fix which picks the middle ground between those two attributes and flags that it's an estimate

**Comment by mcbgun** [comment]
Great stuff. Let me know when you've had chance to complete and I'll test.

**Comment by olimorris** [comment]
Right, I've just pushed a fix. If you run `pip install --upgrade pyscoutfm` in a few minutes it should install `v1.1.0`.

I ran it on your html file and it worked fine.

**Comment by mcbgun** [comment]
Yes confirmed...works perfectly thank you so much!
